backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "images/uploads"

collections:
  - name: "timeline_items"
    label: "Timeline Items"
    folder: "static/timeline_items"
    create: true
    slug: "{{date}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Path", name: "path", widget: "string", default: "/" }
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown" }